sbatch /home/XXXXX/neuralogic/experiments/digits_gnn/scripts/molecules_MDA_MB_231_ATCC_molecules_GNN_template_embeddings__-iso_1_-prune_1_-xval_5_-isocheck_-1_-isoinits_1_-ts_10.sh
sbatch /home/XXXXX/neuralogic/experiments/digits_gnn/scripts/molecules_MDA_MB_231_ATCC_molecules_GNN_template_embeddings__-iso_2_-prune_1_-xval_5_-isocheck_-1_-isoinits_1_-ts_10.sh
sbatch /home/XXXXX/neuralogic/experiments/digits_gnn/scripts/molecules_MDA_MB_231_ATCC_molecules_GNN_template_embeddings__-iso_3_-prune_1_-xval_5_-isocheck_-1_-isoinits_1_-ts_10.sh
sbatch /home/XXXXX/neuralogic/experiments/digits_gnn/scripts/molecules_MDA_MB_231_ATCC_molecules_GNN_template_embeddings__-iso_4_-prune_1_-xval_5_-isocheck_-1_-isoinits_1_-ts_10.sh
