sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_A498_molecules_LRNN_template_embeddings__-iso_-1_-prune_-1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_A498_molecules_LRNN_template_embeddings__-iso_14_-prune_-1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_A498_molecules_LRNN_template_embeddings__-iso_-1_-prune_1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_A498_molecules_LRNN_template_embeddings__-iso_14_-prune_1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_A549_ATCC_molecules_LRNN_template_embeddings__-iso_-1_-prune_-1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_A549_ATCC_molecules_LRNN_template_embeddings__-iso_14_-prune_-1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_A549_ATCC_molecules_LRNN_template_embeddings__-iso_-1_-prune_1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_A549_ATCC_molecules_LRNN_template_embeddings__-iso_14_-prune_1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_786_0_molecules_LRNN_template_embeddings__-iso_-1_-prune_-1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_786_0_molecules_LRNN_template_embeddings__-iso_14_-prune_-1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_786_0_molecules_LRNN_template_embeddings__-iso_-1_-prune_1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_786_0_molecules_LRNN_template_embeddings__-iso_14_-prune_1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_MDA_MB_231_ATCC_molecules_LRNN_template_embeddings__-iso_-1_-prune_-1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_MDA_MB_231_ATCC_molecules_LRNN_template_embeddings__-iso_14_-prune_-1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_MDA_MB_231_ATCC_molecules_LRNN_template_embeddings__-iso_-1_-prune_1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
sbatch /home/XXXXX/neuralogic/experiments/lossless_lrnn/scripts/molecules_MDA_MB_231_ATCC_molecules_LRNN_template_embeddings__-iso_14_-prune_1_-opt_adam_-lr_0.01_-xval_5_-ts_1000.sh
